### ISSUE TITLE
When I change teams during a round bright skins don't change with me

### ISSUE THREAD

**Issue by plainbum** [zenakuten/WS3SPN#2]
When I change teams to balance them during around my bright skins don't change accordingly but they do change after the round is over.

**Comment by zenakuten** [comment]
Since WSUTComp handles brightskins, this is an issue with WSUTComp.

Fix is [here](https://github.com/zenakuten/WSUTComp/commit/dedeea737eaeb2e9c9010366dac8f3b712803b1c) and will be in next release.
